apiVersion: v1
kind: Namespace
metadata:
  name: tkn-dash

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tkn-dash
  labels:
    app.kubernetes.io/component: dashboard
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tkn-dash
rules:
  - apiGroups:
      - ''
    resources:
      - events
      - namespaces
      - pods
      - pods/log
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - tekton.dev
    resources:
      - tasks
      - taskruns
      - pipelines
      - pipelineruns
      - customruns
    verbs:
      - get
      - list
      - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tkn-dash
  namespace: tkn-dash
  labels:
    app.kubernetes.io/component: dashboard
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tkn-dash
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tkn-dash
  labels:
    app.kubernetes.io/component: dashboard
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tkn-dash
    rbac.dashboard.tekton.dev/subject: tkn-dash
subjects:
  - kind: ServiceAccount
    name: tkn-dash
    namespace: tkn-dash
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tkn-dash

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tkn-dash
  namespace: tkn-dash
  labels:
    app.kubernetes.io/name: dashboard
    app.kubernetes.io/component: dashboard
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: devel
    app.kubernetes.io/part-of: tkn-dash
    app: tkn-dash
    version: "devel"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dashboard
      app.kubernetes.io/component: dashboard
      app.kubernetes.io/instance: default
      app.kubernetes.io/part-of: tkn-dash
  template:
    metadata:
      name: tkn-dash
      labels:
        app.kubernetes.io/name: dashboard
        app.kubernetes.io/component: dashboard
        app.kubernetes.io/instance: default
        app.kubernetes.io/version: devel
        app.kubernetes.io/part-of: tkn-dash
        app: tkn-dash
    spec:
      serviceAccountName: tkn-dash
      volumes: []
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: tkn-dash
          image: cezarguimaraes/tkn-dash:vdev
          ports:
            - containerPort: 8000
              #livenessProbe:
              #httpGet:
              #path: /health
              #port: 9097
              #readinessProbe:
              #httpGet:
              #path: /readiness
              #port: 9097
          args:
            - -addr=:8000
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
            runAsUser: 65532
            runAsGroup: 65532
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault

---
